### ISSUE TITLE
cannot import name 'mtls'

### ISSUE THREAD

**Issue by nitramsivart** [googleapis/google-api-python-client#933]
This appears to be a bug with version 1.9 caused by https://github.com/googleapis/google-api-python-client/pull/917

#### Environment details

  - OS type and version: OS X 10.15.4
  - Python version: `3.6.10`
  - pip version: `20.0.02`
  - `google-api-python-client` version: `1.9.1`

#### Steps to reproduce

  1. python -c "import googleapiclient.discovery"

#### Stack trace
```
----> 1 import googleapiclient.discovery

~/miniconda3/envs/surround-cp/lib/python3.6/site-packages/googleapiclient/discovery.py in <module>
     48 import uritemplate
     49 import google.api_core.client_options
---> 50 from google.auth.transport import mtls
     51 from google.auth.exceptions import MutualTLSChannelError
     52

ImportError: cannot import name 'mtls'
```

**Comment by nitramsivart** [comment]
CC: @busunkim96 , @arithmetic1728

**Comment by nitramsivart** [comment]
I see that my `google-auth` version is old (`1.6.3`), so maybe this is actually an issue of my not upgrading all dependencies properly.

**Comment by arithmetic1728** [comment]
@nitramsivart yes, please upgrade `google-auth`. `mtls` is not defined in the old version.

**Comment by nitramsivart** [comment]
Thank you, that resolved my issue!

**Comment by nitramsivart** [comment]
Note, this is still an issue upon conda-install: https://github.com/conda-forge/google-api-python-client-feedstock/issues/39

**Comment by busunkim96** [comment]
Hmm, I'm not entirely sure how this package is published to conda. @meredithslota?

**Comment by nitramsivart** [comment]
Pretty sure it's published using `conda-smithy`, as described a bit more in README of this reop: https://github.com/conda-forge/google-api-python-client-feedstock

What's unclear to me is if anybody owns keeping this up to date, or it's just as needed

**Comment by busunkim96** [comment]
Closing as this has been addressed by the folks who manage the repo mentioned above.

**Comment by A-Sm1th** [comment]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-61-286c2210acad> in <module>
      4 import httplib2
      5 
----> 6 from googleapiclient.discovery import build
      7 
      8 SCOPES = [

~/.local/lib/python3.6/site-packages/googleapiclient/discovery.py in <module>
     48 import uritemplate
     49 import google.api_core.client_options
---> 50 from google.auth.transport import mtls
     51 from google.auth.exceptions import MutualTLSChannelError
     52 

ImportError: cannot import name 'mtls'`

I still get the error even though my `pip list` shows the version `google-auth              1.17.2`

**Comment by busunkim96** [comment]
@A-Sm1th Can you double check the version? The latest published version is [`1.9.2`](https://github.com/googleapis/google-api-python-client/releases/tag/v1.9.3)

**Comment by arithmetic1728** [comment]
@A-Sm1th I tested `google-auth 1.17.2` and it worked fine. 

```
(tmp) $ python -m pip freeze
cachetools==4.1.0
google-auth==1.17.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
rsa==4.6
six==1.15.0
(tmp) $ python
Python 3.6.9 (default, Jan 26 2020, 20:47:45) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.auth.transport import mtls
>>> 
```

**Comment by nitramsivart** [comment]
Why is this being assigned to me?

**Comment by arithmetic1728** [comment]
This issue is already closed, not sure what happened to the assignment.

**Comment by akram-ali-cs** [comment]
google-api-python-client version: 2.2.0

From yesterday getting this error, I've updated with the latest version as well.

**Comment by arithmetic1728** [comment]
@akram-ali-cs I just tested 2.2.0, it worked fine. Maybe you need to update `google-auth` to latest version.

```
$ python
Python 3.7.6 (default, Jun 22 2020, 13:51:33) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.auth.transport import mtls
```

**Comment by fisakhan** [comment]
This is still a problem for me. Even after installing the latest version of google-auth, I get the following error.
```
$ pip install google_auth
Installing collected packages: google-auth
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth~=1.4.0, but you have google-auth 1.32.0 which is incompatible.
google-api-python-client 1.12.8 requires six<2dev,>=1.13.0, but you have six 1.12.0 which is incompatible.
google-api-core 1.30.0 requires six>=1.13.0, but you have six 1.12.0 which is incompatible.
Successfully installed google-auth-1.32.0
```
I already have the following installed versions:
```
google-colab==1.0.0
tensorflow==2.5.0
tensorflow-cloud==0.1.16
```

**Comment by parthea** [comment]
Hi @ fisakhan,
For `google-api-python-client`, the following error is valid:
`google-api-python-client 1.12.8 requires six<2dev,>=1.13.0, but you have six 1.12.0 which is incompatible.`

`six>=1.13.0 is required` in the `google-api-python-client` [setup.py file](https://github.com/googleapis/google-api-python-client/blob/master/setup.py#L39). Simply run `pip install six==1.13.0`.

**Comment by fisakhan** [comment]
Now I get the following error:
```
$ pip install six==1.13.0
Collecting six==1.13.0
  Downloading six-1.13.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires six~=1.15.0, but you have six 1.13.0 which is incompatible.
google-colab 1.0.0 requires google-auth~=1.4.0, but you have google-auth 1.32.0 which is incompatible.
google-colab 1.0.0 requires six~=1.12.0, but you have six 1.13.0 which is incompatible.
cookiecutter 1.7.3 requires requests>=2.23.0, but you have requests 2.21.0 which is incompatible.
apache-beam 2.30.0 requires requests<3.0.0,>=2.24.0, but you have requests 2.21.0 which is incompatible.
Successfully installed six-1.13.0
```

**Comment by parthea** [comment]
I see. Yes, it looks the [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release) `~=` requirement for `tensorflow` and `google-colab` is going to cause a problem. 

In `google-api-python-client` the requirement is `six>=1.13.0,<2dev` so any version `1.13.0` or higher but less than `2dev` will work. 
In `tensorflow`, the requirement is `six~=1.15.0`, so only versions like `1.15.*` will work
In `google-colab`, the requirement is `six~=1.12.0`, so only versions like `1.12.*` will work

Please open an issue in the respective repos as there is no improvement for this repo.
